### ISSUE TITLE
Using node:alpine as base image?

### ISSUE THREAD

**Issue by misolietavec** [jupyterhub/configurable-http-proxy#102]
With setting the base image to node:alpine and building the docker container I got image of size 61 MB,
whilst the node:5-slim image has size 209 MB. I am testing Alpine Linux based image in Jupyter tmpnb notebooks on our university server, no problems as for now.
 
My consideration is not only about size. node:alpine has 13 (apk installed) packages, each of them really necessary but "slim" variant (debian based) has 135 packages, some of them very superfluous in this concrete case (in reality, I am debian user for many years...).   

Are there any reasons not to use node:alpine as the base image?

**Comment by willingc** [comment]
Hi @misolietavec,

Thanks for the suggestion. I'm glad that Alpine Linux is working well for you on your university server. I suspect the slim variant was chosen due to both popularity and stability. While @minrk may have additional thoughts, two reasons to perhaps not use Alpine as the base image is the surrounding GPL confusion re: BusyBox and lack of full compatibility with glibc.

I'm going to label this issue as reference since others may find the use of Alpine helpful. @minrk, I would recommend closing this issue as currently out of scope (due to licensing), but leaving it for you to decide.

**Comment by minrk** [comment]
Since a CHP image should only be used to run CHP itself (it's a pretty trivial install into any existing image, so it ~never makes sense to use it as a base image), an alpine-based image makes sense to me. Feel free to make a PR!

**Comment by minrk** [comment]
@misolietavec thanks! alpine is now the default.
