### ISSUE TITLE
Rewrite project in Python3 to get rid of NodeJS dependency

### ISSUE THREAD

**Issue by nfx** [jupyterhub/configurable-http-proxy#143]
In enterprise environments it's often a problem to maintain different ecosystems, such as NodeJS. Jupyterhub is written in Python, so I don't really see a big reason to have NodeJS along, which makes life of maintainers and internal package repository maintainers harder. 

I'd suggest scheduling `configurable-http-proxy` rewrite to Python given viable API backwards compatible replacement available.

**Comment by minrk** [comment]
I, too, wish this could have been Python! But it was vastly simpler to extend the existing node-http-proxy than to reimplement a proxy in Python. Node.js was chosen specifically because it makes the lives of maintainers of jupyterhub easier, despite it not being in our language of choice. Right now, installing node.js is a whole lot less work that writing and maintaining a whole new proxy. CHP sits on an existing proxy, so the only bit we maintain is the `configurable-` in configurable-http-proxy, making this a very small and low-maintenance project. Which is very important when we are a small team spread across many projects.

If you have different requirements, JupyterHub allows any proxy implementation now, so it is possible to write a Python proxy for JupyterHub. There is one [in nginx](https://github.com/yuvipanda/jupyterhub-nginx-chp) and one [for kubernetes ingress](https://github.com/jupyterhub/kubespawner/pull/64).

If you want to write and maintain a Python proxy, I'm sure that would make some folks happy, but since it would greatly increase our maintenance burden here, it is not planned.

[nbrserverproxy](https://github.com/jupyterhub/nbserverproxy) is on its way to implementing most of the necessary features, but with less performance considerations since it's one per user.

**Comment by nfx** [comment]
@minrk thanks for NCHP reference! probably it's the thing that is better than writing own with Python. It took couple of hours to actually get basic API and functionality working with approach similar to nbrserverproxy. I'm also glad to hear than JupyterHub now supports different proxy commands - we haven't updated the version for about a year and now it's the time.
