### ISSUE TITLE
YARN gateway

### ISSUE THREAD

**Issue by martindurant** [jupyterhub/configurable-http-proxy#167]
In the context of [skein](https://github.com/jcrist/skein) we would be interested in using this project as a dynamic gateway for dask clusters on a YARN deployment. `skein` would be accessible from the outside (on an "edge node") and handle talking to YARN to create scheduler/worker containers that are unreachable from the outside.

I am thinking that `configurable-http-proxy` could be called by `skein` to map a URL such that users can establish TCP connections with schedulers within the cluster, from outside the cluster.

Is this a reasonable use case for `configurable-http-proxy`? Given that we can handle the `skein` side to make appropriate REST calls and pass URLs back to the user, how much work would it be to set up such a configuration?

**Comment by martindurant** [comment]
cc @jcrist @mrocklin

**Comment by mrocklin** [comment]
Quick question, but does the fact that Dask communications happen over TCP and not over HTTP raise challenges here?

**Comment by jcrist** [comment]
Yes, from reading the repo-name/source/docs, this appears to only support proxying http(s) requests, and wouldn't be valid for this use case. It's also not clear how you would proxy tcp over a single `address:port`, since there's no further path in the address to map the requests on. I think we'll have to build something custom, maybe using similar technology but not this. That said, we'd also want to forward things like the dask dashboard, which could use exactly this.
