### ISSUE TITLE
Issues in serving static files

### ISSUE THREAD

**Issue by akhilputhiry** [jupyterhub/configurable-http-proxy#171]
I am trying to use `configurable-http-proxy` for proxying user specific ML flow dashboards generated by running `mlflow ui`. But the proxy fails in serving static files. I see two problems here,
* Path rewriting is not taken care
* Even if I try to access the correct path manually, It fails

**Comment by minrk** [comment]
CHP doesn't rewrite paths, it preserves them. It's meant for proxying applications that understand their base path, so that they route appropriately.

You might be after the `--no-include-prefix` flag, which omits the routing prefix from the forwarded request. This would break any absolute URL handling in the proxied application, though.
