### ISSUE TITLE
allow routing of sockjs

### ISSUE THREAD

**Issue by yee379** [jupyterhub/configurable-http-proxy#203]
not sure how to start with this. so i have an app that is spawned via a container in juptyerhub. it spins up a web application based off meteor.js. after fiddling with some statics and kubernetes ingress routing i am able to get the app up....

so in jupyterhub, i go:

    https://jupyter-dev/user/ytl/proxy/39000/

and it mostly loads up.

the issue is that it also needs a websocket connection. unfortunately, it seems to want to use:

    https://jupyter-dev/sockjs/info?cb=mg0uu3ucnl

is there a way i can configure the proxy to look at the cookie to determine that `/sockjs` should be redirected to the the spawned container?

this may be related to [issue 90](https://github.com/jupyterhub/configurable-http-proxy/issues/90)

**Comment by minrk** [comment]
This would be due to sockjs using the wrong url path, and not something that CHP should be dealikng with. Instead of `/sockjs` it should be using `/user/ytl/sockjs`. In a Jupyter application, this prefix is called `base_url` and available from state/env/configuration. Can you tell where the sockjs code is creating its url? That's what needs to be updated.
