### ISSUE TITLE
Scale the configurable-http-proxy to handle 1000 connections 

### ISSUE THREAD

**Issue by mainak24** [jupyterhub/configurable-http-proxy#465]
Hi team,

We have a use case where we have 1000+ concurrent connections to the proxy from the hub. How to add multiple configurable-http-proxy and have a Load Balancer to load balance connections to multiple proxy server

**Comment by consideRatio** [comment]
The routing is controlled by JupyterHub via a REST API, which only influences one instance - due to that, you can't have multiple replicas setup setup easily. This relates to a larger issue of making jupyterhub support being run in a "highly available" mode. See https://github.com/jupyterhub/jupyterhub/issues/1932 for more information.
